### ISSUE TITLE
Google calendar API research

### ISSUE THREAD

**Issue by LeonoraXu** [CHCTS-Microservices/TimeTracker#18]
Due 1/9/2023 12:00am [https://developers.google.com/calendar/api/guides/overview](url)

**Comment by Artic13** [comment]
hey hows the progress going?

**Comment by Artic13** [comment]
Hey, hows the work going?

**Comment by LeonoraXu** [comment]
Decided to use FullCalendar, which has all the features and no need to go through the API thing

**Comment by Artic13** [comment]
cool great
