### ISSUE TITLE
feature/main-selectedEvent

### ISSUE THREAD

**Issue by Artic13** [CHCTS-Microservices/TimeTracker#46]

**Comment by Artic13** [comment]
- [ ] when an event is selected, it should update main form

**Comment by Artic13** [comment]
hows the work going?

**Comment by YitaoZhang-2020** [comment]
I am doing it

**Comment by Artic13** [comment]
where is the pull request?

**Comment by Artic13** [comment]
Apologies i made a mistake in the merge. we need to try revert your implementation.
