### ISSUE TITLE
Internal Team testing

### ISSUE THREAD

**Issue by Artic13** [CHCTS-Microservices/TimeTracker#71]

**Comment by Artic13** [comment]
Test UI 

- [ ] Record issues encounter at in the testing docs

**Comment by Artic13** [comment]
Testers will need to test all UI functionality of the application thoroughly. They will need to record any issues encountered in the testing docs. They will need to assess the functionality against the acceptance criteria.

**Comment by LeonoraXu** [comment]
Move the issues raised in final check to internal testing
